/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mock from "./Mock";
export type { mock };
export type { IBlast } from "./IBlast";
export type { ILongStarKey } from "./ILongStarKey";
export type { ILongStarShareV1 } from "./ILongStarShareV1";
export type { LongStarKey } from "./LongStarKey";
export type { LongStarShareV1 } from "./LongStarShareV1";
